project_id = "oysjpeewsgwgnvvpbghe"

[functions.admin-create-student]
verify_jwt = false

[functions.mark-attendance]
verify_jwt = false

[functions.finalize-attendance]
verify_jwt = false

[functions.admin-generate-attendance]
verify_jwt = false

[functions.ensure-admin-account]
verify_jwt = false

[functions.notification-scheduler]
verify_jwt = false

[functions.admin-backfill-user-roles]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.recompute-intelligence]
verify_jwt = false

[functions.daily-content-cron]
verify_jwt = false

[functions.admin-update-attendance]
verify_jwt = false

[functions.retention-on-login]
verify_jwt = false
