/**
 * CAMPUS CONNECT — Centralized Semantic Icon Map
 *
 * All icons use Hugeicons (@hugeicons/core-free-icons) in Stroke Rounded style (default strokeWidth: 1.5).
 * Navigation & key actions support active (elevated weight/filled) state pairs.
 */

import {
  // Navigation & Core
  Home01Icon,
  Home02Icon,
  DashboardSquare01Icon,
  DashboardSquare02Icon,
  Calendar01Icon,
  Calendar02Icon,
  Calendar03Icon,
  CalendarCheckIcon,
  CalendarPlusIcon,
  Clock01Icon,
  Clock02Icon,
  Timer01Icon,
  AlarmClockIcon,
  Search01Icon,
  Search02Icon,
  Menu01Icon,
  Menu02Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  ArrowDown01Icon,
  ArrowUpDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronDownIcon,
  ChevronUpIcon,

  // Academics & Learning
  Book01Icon,
  Book02Icon,
  BookOpen01Icon,
  BookOpen02Icon,
  Mortarboard01Icon,
  Mortarboard02Icon,
  UniversityIcon,
  Building01Icon,
  Building02Icon,
  Building03Icon,
  Brain01Icon,
  Brain02Icon,
  TestTube01Icon,
  File01Icon,
  File02Icon,
  FileSpreadsheetIcon,
  FileValidationIcon,
  FileTypeIcon,
  Task01Icon,
  ClipboardCheckIcon,
  ClipboardListIcon,

  // Users & Identity
  UserIcon,
  User02Icon,
  User03Icon,
  UserGroupIcon,
  UserMultipleIcon,
  UserCheck01Icon,
  UserCheck02Icon,
  UserAdd01Icon,
  UserMinus01Icon,
  UserSettings01Icon,
  UserSettings02Icon,
  UserCircleIcon,
  UserCircle02Icon,
  UserEdit01Icon,
  IdentityCardIcon,
  IdIcon,
  FingerPrintIcon,

  // Status & Alerts
  CheckmarkCircle01Icon,
  CheckmarkCircle02Icon,
  CheckmarkSquare01Icon,
  CheckmarkBadge01Icon,
  CheckmarkBadge02Icon,
  Tick01Icon,
  Tick02Icon,
  TickDouble01Icon,
  TickDouble02Icon,
  Cancel01Icon,
  Cancel02Icon,
  CancelCircleIcon,
  CancelSquareIcon,
  Alert01Icon,
  Alert02Icon,
  AlertDiamondIcon,
  AlertCircleIcon,
  InformationCircleIcon,
  InformationSquareIcon,
  MinusSignIcon,
  MinusSignCircleIcon,
  PlusSignIcon,
  PlusSignCircleIcon,
  CircleIcon,
  CircleDotIcon,
  StopCircleIcon,
  PauseCircleIcon,

  // Actions & Controls
  PencilEdit01Icon,
  PencilEdit02Icon,
  Edit01Icon,
  Delete01Icon,
  Delete02Icon,
  FloppyDiskIcon,
  SaveIcon,
  Download01Icon,
  Download02Icon,
  Upload01Icon,
  Upload02Icon,
  CloudUploadIcon,
  RefreshIcon,
  ReloadIcon,
  ArrowReloadHorizontalIcon,
  RotateLeft01Icon,
  UndoIcon,
  Copy01Icon,
  Copy02Icon,
  Share01Icon,
  Share02Icon,
  ViewIcon,
  ViewOffIcon,
  EyeIcon,
  EyeOffIcon,
  FilterIcon,
  FilterHorizontalIcon,
  Sorting01Icon,
  Sorting02Icon,
  PreferenceHorizontalIcon,
  MoreHorizontalIcon,
  MoreHorizontalCircle01Icon,
  MoreVerticalIcon,
  MoreVerticalCircle01Icon,
  ExternalLinkIcon,
  Link01Icon,
  AttachmentIcon,
  PinIcon,
  Tag01Icon,
  PrinterIcon,
  DragDropVerticalIcon,
  SidebarLeftIcon,
  ArchiveIcon,

  // Gamification & Rewards
  ChampionIcon,
  Award01Icon,
  Award02Icon,
  Medal01Icon,
  Coins01Icon,
  Coins02Icon,
  StarIcon,
  FavouriteIcon,
  SparklesIcon,
  MagicWand01Icon,
  FlashIcon,
  EnergyIcon,
  FireIcon,
  Target01Icon,
  PartyIcon,
  GiftIcon,
  Rocket01Icon,
  Rocket02Icon,

  // Communication
  Notification01Icon,
  Notification02Icon,
  Notification03Icon,
  NotificationOff01Icon,
  Megaphone01Icon,
  Megaphone02Icon,
  Comment01Icon,
  Comment02Icon,
  CommentAdd01Icon,
  ChatFavourite01Icon,
  BubbleChatFavouriteIcon,
  InboxIcon,
  InboxUnreadIcon,
  Mail01Icon,
  Mail02Icon,
  MailOpen01Icon,
  CallIcon,
  CallIncoming01Icon,

  // Security & Settings
  Shield01Icon,
  Shield02Icon,
  SecurityCheckIcon,
  LockIcon,
  CircleUnlock01Icon,
  Key01Icon,
  Key02Icon,
  Settings01Icon,
  Settings02Icon,
  Logout01Icon,
  Logout02Icon,
  Login01Icon,
  Login02Icon,

  // Analytics & Charts
  TradeUpIcon,
  TradeDownIcon,
  AnalyticsUpIcon,
  AnalyticsDownIcon,
  Analytics01Icon,
  ChartHistogramIcon,
  Activity01Icon,
  PulseIcon,
  Radar01Icon,

  // Platform & Campus
  GlobeIcon,
  Globe02Icon,
  Database01Icon,
  Database02Icon,
  ServerStack01Icon,
  ServerStack02Icon,
  HierarchyIcon,
  Wifi01Icon,
  WifiOff01Icon,
  SmartPhone01Icon,
  SmartPhone02Icon,
  LaptopIcon,
  ComputerIcon,
  GridIcon,
  Grid02Icon,
  Layers01Icon,
  Layers02Icon,
  LeftToRightListBulletIcon,
  HashtagIcon,
  QrCode01Icon,
  QrCodeScanIcon,
  ScanIcon,
  Sun01Icon,
  Sun02Icon,
  Moon01Icon,
  Moon02Icon,
  BulbIcon,
  HelpCircleIcon,
  LifebuoyIcon,
  Bug01Icon,
  PaintBoardIcon,
  HistoryIcon,
  Loading01Icon,
  Loading02Icon,
  Store01Icon,
  ShoppingBag01Icon,
  CreditCardIcon,
  Briefcase01Icon,
  Location01Icon,
  Location02Icon,
  Location03Icon,
  Image01Icon,
  Camera01Icon,
  CameraOff01Icon,
  Video01Icon,
  PlayIcon,
  PlayCircleIcon,
  Ticket01Icon,
  Radio01Icon,
  Radio02Icon,
  SentIcon,
  Sent02Icon,
} from "@hugeicons/core-free-icons";

import type { IconSvgElement } from "@hugeicons/react";

/**
 * Standard semantic icon definitions.
 * Each entry maps a semantic name to an inactive (stroke) and active (filled/elevated) icon.
 */
export interface SemanticIconPair {
  inactive: IconSvgElement;
  active: IconSvgElement;
}

export const SEMANTIC_ICON_MAP = {
  // ── CORE NAVIGATION ────────────────────────────────────────────────
  home: { inactive: Home01Icon, active: Home02Icon },
  dashboard: { inactive: DashboardSquare01Icon, active: DashboardSquare02Icon },
  timetable: { inactive: Calendar03Icon, active: Calendar01Icon },
  attendance: { inactive: CheckmarkSquare01Icon, active: CheckmarkCircle01Icon },
  assignments: { inactive: Task01Icon, active: ClipboardCheckIcon },
  results: { inactive: ChartHistogramIcon, active: AnalyticsUpIcon },
  events: { inactive: Calendar03Icon, active: Ticket01Icon },
  notifications: { inactive: Notification01Icon, active: Notification02Icon },
  messages: { inactive: Comment01Icon, active: Comment02Icon },
  profile: { inactive: UserIcon, active: User02Icon },
  settings: { inactive: Settings01Icon, active: Settings02Icon },
  help: { inactive: HelpCircleIcon, active: LifebuoyIcon },
  search: { inactive: Search01Icon, active: Search02Icon },
  menu: { inactive: Menu01Icon, active: Menu02Icon },
  back: { inactive: ArrowLeft01Icon, active: ArrowLeft01Icon },
  forward: { inactive: ArrowRight01Icon, active: ArrowRight01Icon },

  // ── ACADEMICS ──────────────────────────────────────────────────────
  courses: { inactive: Book01Icon, active: Book02Icon },
  subjects: { inactive: BookOpen01Icon, active: BookOpen02Icon },
  faculty: { inactive: UserMultipleIcon, active: UserGroupIcon },
  departments: { inactive: Building01Icon, active: Building02Icon },
  classes: { inactive: UserGroupIcon, active: UserGroupIcon },
  lectures: { inactive: Mortarboard01Icon, active: Mortarboard02Icon },
  study_material: { inactive: File01Icon, active: File02Icon },
  documents: { inactive: File01Icon, active: File02Icon },

  // ── ATTENDANCE ─────────────────────────────────────────────────────
  present: { inactive: CheckmarkCircle01Icon, active: CheckmarkCircle02Icon },
  absent: { inactive: CancelCircleIcon, active: CancelSquareIcon },
  late: { inactive: Clock01Icon, active: Clock02Icon },
  attendance_summary: { inactive: ChartHistogramIcon, active: Analytics01Icon },
  qr_attendance: { inactive: QrCode01Icon, active: QrCodeScanIcon },
  location_verification: { inactive: Location01Icon, active: Location02Icon },
  attendance_history: { inactive: Calendar03Icon, active: CalendarCheckIcon },

  // ── GAMIFICATION ───────────────────────────────────────────────────
  points: { inactive: Coins01Icon, active: Coins02Icon },
  leaderboard: { inactive: ChampionIcon, active: ChampionIcon },
  achievements: { inactive: Award01Icon, active: Medal01Icon },
  streak: { inactive: FireIcon, active: FireIcon },
  rewards: { inactive: GiftIcon, active: PartyIcon },
  challenges: { inactive: Target01Icon, active: Target01Icon },

  // ── EVENTS ─────────────────────────────────────────────────────────
  event: { inactive: Calendar03Icon, active: CalendarCheckIcon },
  registration: { inactive: ClipboardCheckIcon, active: Task01Icon },
  venue: { inactive: Location01Icon, active: Location02Icon },
  participants: { inactive: UserGroupIcon, active: UserMultipleIcon },
  ticket: { inactive: Ticket01Icon, active: Ticket01Icon },
  event_manager: { inactive: CalendarPlusIcon, active: Calendar01Icon },

  // ── ADMIN ──────────────────────────────────────────────────────────
  students: { inactive: UserGroupIcon, active: UserMultipleIcon },
  verification: { inactive: SecurityCheckIcon, active: Shield01Icon },
  kyc: { inactive: IdentityCardIcon, active: IdIcon },
  analytics: { inactive: Analytics01Icon, active: ChartHistogramIcon },
  reports: { inactive: File01Icon, active: FileSpreadsheetIcon },
  audit_logs: { inactive: Activity01Icon, active: HistoryIcon },
  security: { inactive: Shield01Icon, active: Shield02Icon },
  permissions: { inactive: LockIcon, active: Key01Icon },
  system_settings: { inactive: Settings01Icon, active: Settings02Icon },
  platform: { inactive: Globe02Icon, active: Layers01Icon },

  // ── COMMUNICATION ──────────────────────────────────────────────────
  announcement: { inactive: Megaphone01Icon, active: Megaphone02Icon },
  notification: { inactive: Notification01Icon, active: Notification02Icon },
  message: { inactive: Comment01Icon, active: Comment02Icon },
  email: { inactive: Mail01Icon, active: MailOpen01Icon },
  push_notification: { inactive: Notification01Icon, active: Notification03Icon },
  support: { inactive: HelpCircleIcon, active: LifebuoyIcon },
  feedback: { inactive: BubbleChatFavouriteIcon, active: StarIcon },
  send: { inactive: SentIcon, active: Sent02Icon },

  // ── ACTIONS ────────────────────────────────────────────────────────
  add: { inactive: PlusSignIcon, active: PlusSignCircleIcon },
  edit: { inactive: PencilEdit01Icon, active: Edit01Icon },
  delete: { inactive: Delete01Icon, active: Delete02Icon },
  save: { inactive: FloppyDiskIcon, active: SaveIcon },
  download: { inactive: Download01Icon, active: Download02Icon },
  upload: { inactive: Upload01Icon, active: Upload02Icon },
  share: { inactive: Share01Icon, active: Share02Icon },
  copy: { inactive: Copy01Icon, active: Copy02Icon },
  refresh: { inactive: RefreshIcon, active: ReloadIcon },
  filter: { inactive: FilterIcon, active: FilterHorizontalIcon },
  sort: { inactive: Sorting01Icon, active: Sorting02Icon },
  more: { inactive: MoreHorizontalIcon, active: MoreHorizontalCircle01Icon },
  close: { inactive: Cancel01Icon, active: CancelCircleIcon },
  confirm: { inactive: Tick01Icon, active: CheckmarkCircle01Icon },
  warning: { inactive: Alert01Icon, active: AlertDiamondIcon },
  error: { inactive: AlertCircleIcon, active: CancelCircleIcon },
  success: { inactive: CheckmarkCircle01Icon, active: CheckmarkBadge01Icon },

  // ── STATUS ICONS ───────────────────────────────────────────────────
  status_success: { inactive: CheckmarkCircle01Icon, active: CheckmarkCircle01Icon },
  status_pending: { inactive: Clock01Icon, active: Clock01Icon },
  status_warning: { inactive: Alert01Icon, active: Alert01Icon },
  status_error: { inactive: AlertCircleIcon, active: AlertCircleIcon },
  status_verified: { inactive: SecurityCheckIcon, active: SecurityCheckIcon },
  status_unverified: { inactive: Shield01Icon, active: Shield01Icon },
  status_locked: { inactive: LockIcon, active: LockIcon },
  status_unlocked: { inactive: CircleUnlock01Icon, active: CircleUnlock01Icon },
} as const;

export type SemanticIconName = keyof typeof SEMANTIC_ICON_MAP;

/**
 * Direct legacy-to-hugeicon translation mapping for all 180 Lucide icons
 * ensuring 100% complete replacement across the entire codebase.
 */
export const LUCIDE_TO_HUGEICON_MAP: Record<string, IconSvgElement> = {
  // Navigation & Shell
  Home: Home01Icon,
  LayoutDashboard: DashboardSquare01Icon,
  Calendar: Calendar03Icon,
  CalendarDays: Calendar03Icon,
  CalendarCheck: CalendarCheckIcon,
  CalendarClock: Calendar03Icon,
  CalendarPlus: CalendarPlusIcon,
  CalendarHeart: Calendar03Icon,
  CalendarRange: Calendar03Icon,
  Clock: Clock01Icon,
  Clock3: Clock01Icon,
  Timer: Timer01Icon,
  AlarmClock: AlarmClockIcon,
  Menu: Menu01Icon,
  PanelLeft: SidebarLeftIcon,

  // Academics
  BookOpen: BookOpen01Icon,
  BookOpenCheck: BookOpen01Icon,
  GraduationCap: Mortarboard01Icon,
  School: UniversityIcon,
  Brain: Brain01Icon,
  FlaskConical: TestTube01Icon,

  // Users & Identity
  Users: UserGroupIcon,
  User: UserIcon,
  UserRound: UserIcon,
  UserCheck: UserCheck01Icon,
  UserRoundCheck: UserCheck01Icon,
  UserPlus: UserAdd01Icon,
  UserX: UserMinus01Icon,
  UserCog: UserSettings01Icon,
  UserCircle: UserCircleIcon,
  UserCircle2: UserCircle02Icon,
  UserPen: UserEdit01Icon,
  IdCard: IdentityCardIcon,
  Fingerprint: FingerPrintIcon,

  // Status & Feedback
  Check: Tick01Icon,
  CheckCheck: TickDouble01Icon,
  CheckCircle: CheckmarkCircle01Icon,
  CheckCircle2: CheckmarkCircle01Icon,
  CheckSquare: CheckmarkSquare01Icon,
  BadgeCheck: CheckmarkBadge01Icon,
  AlertCircle: AlertCircleIcon,
  AlertTriangle: Alert01Icon,
  TriangleAlert: Alert01Icon,
  X: Cancel01Icon,
  XCircle: CancelCircleIcon,
  MinusCircle: MinusSignCircleIcon,
  PlusCircle: PlusSignCircleIcon,
  ArrowUpCircle: ArrowUp01Icon,
  Minus: MinusSignIcon,
  Plus: PlusSignIcon,
  Circle: CircleIcon,
  Dot: CircleDotIcon,
  StopCircle: StopCircleIcon,
  PauseCircle: PauseCircleIcon,

  // Actions & Controls
  Search: Search01Icon,
  Filter: FilterIcon,
  SlidersHorizontal: PreferenceHorizontalIcon,
  Pencil: PencilEdit01Icon,
  FileEdit: PencilEdit01Icon,
  Trash2: Delete01Icon,
  Save: FloppyDiskIcon,
  Download: Download01Icon,
  Upload: Upload01Icon,
  UploadCloud: CloudUploadIcon,
  RefreshCw: RefreshIcon,
  RotateCcw: RotateLeft01Icon,
  Undo2: UndoIcon,
  Copy: Copy01Icon,
  Share: Share01Icon,
  Share2: Share01Icon,
  Eye: ViewIcon,
  EyeOff: ViewOffIcon,
  Printer: PrinterIcon,
  Pin: PinIcon,
  Tag: Tag01Icon,
  GripVertical: DragDropVerticalIcon,
  MoreHorizontal: MoreHorizontalIcon,
  MoreVertical: MoreVerticalIcon,

  // Arrows & Direction
  ArrowRight: ArrowRight01Icon,
  ArrowLeft: ArrowLeft01Icon,
  ArrowUp: ArrowUp01Icon,
  ArrowDown: ArrowDown01Icon,
  ArrowUpDown: ArrowUpDownIcon,
  ChevronRight: ChevronRightIcon,
  ChevronLeft: ChevronLeftIcon,
  ChevronDown: ChevronDownIcon,
  ChevronUp: ChevronUpIcon,
  ExternalLink: ExternalLinkIcon,

  // Files & Media
  FileText: File01Icon,
  File: File01Icon,
  FileSpreadsheet: FileSpreadsheetIcon,
  FileCheck2: FileValidationIcon,
  FileType2: FileTypeIcon,
  ClipboardCheck: ClipboardCheckIcon,
  ClipboardList: ClipboardListIcon,
  Image: Image01Icon,
  Camera: Camera01Icon,
  CameraOff: CameraOff01Icon,
  Video: Video01Icon,
  Play: PlayIcon,
  PlayCircle: PlayCircleIcon,
  Paperclip: AttachmentIcon,
  Archive: ArchiveIcon,

  // Gamification & Rewards
  Trophy: ChampionIcon,
  Award: Award01Icon,
  Medal: Medal01Icon,
  Coins: Coins01Icon,
  Star: StarIcon,
  Sparkles: SparklesIcon,
  Wand2: MagicWand01Icon,
  Zap: FlashIcon,
  Flame: FireIcon,
  Target: Target01Icon,
  PartyPopper: PartyIcon,
  Rocket: Rocket01Icon,

  // Communication
  Bell: Notification01Icon,
  BellOff: NotificationOff01Icon,
  Megaphone: Megaphone01Icon,
  MessageSquare: Comment01Icon,
  MessageSquarePlus: CommentAdd01Icon,
  MessageSquareHeart: ChatFavourite01Icon,
  MessageCircle: Comment01Icon,
  Inbox: InboxIcon,
  Mail: Mail01Icon,
  MailOpen: MailOpen01Icon,
  Phone: CallIcon,

  // Security & Settings
  Shield: Shield01Icon,
  ShieldCheck: SecurityCheckIcon,
  ShieldAlert: Shield01Icon,
  ShieldX: Shield01Icon,
  Lock: LockIcon,
  Key: Key01Icon,
  KeyRound: Key01Icon,
  Settings: Settings01Icon,
  Settings2: Settings02Icon,
  LogOut: Logout01Icon,
  LogIn: Login01Icon,

  // Charts & Analytics
  TrendingUp: TradeUpIcon,
  TrendingUpIcon: TradeUpIcon,
  TrendingDown: TradeDownIcon,
  BarChart2: ChartHistogramIcon,
  BarChart3: ChartHistogramIcon,
  ChartLine: AnalyticsUpIcon,
  Activity: Activity01Icon,
  Radar: Radar01Icon,

  // Business & Campus
  Building2: Building01Icon,
  Landmark: UniversityIcon,
  Store: Store01Icon,
  CreditCard: CreditCardIcon,
  Briefcase: Briefcase01Icon,
  MapPin: Location01Icon,

  // Platform & Tech
  Globe: Globe02Icon,
  Database: Database01Icon,
  Server: ServerStack01Icon,
  Network: HierarchyIcon,
  Wifi: Wifi01Icon,
  WifiOff: WifiOff01Icon,
  Smartphone: SmartPhone01Icon,
  Laptop: LaptopIcon,
  MonitorSmartphone: ComputerIcon,
  LayoutGrid: GridIcon,
  Grid3X3: GridIcon,
  LayoutTemplate: GridIcon,
  Layers: Layers01Icon,
  List: LeftToRightListBulletIcon,
  Hash: HashtagIcon,
  QrCode: QrCode01Icon,
  Scan: QrCodeScanIcon,
  ScanLine: ScanIcon,
  Sun: Sun01Icon,
  Moon: Moon01Icon,
  Lightbulb: BulbIcon,
  HelpCircle: HelpCircleIcon,
  LifeBuoy: LifebuoyIcon,
  Info: InformationCircleIcon,
  Bug: Bug01Icon,
  Palette: PaintBoardIcon,
  History: HistoryIcon,
  Loader2: Loading01Icon,
  Radio: Radio01Icon,
  Send: SentIcon,
};
